import "./normalize.scss";
import "./global.scss";
import ThemeButton from "@/components/ThemeButton";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeButton />
        {children}
      </body>
    </html>
  );
}
